### ISSUE TITLE
portfolio website colors 

### ISSUE THREAD

**Issue by jeremiah-louis** [Tegacreatives/personal-site#2]
Title:
**Inconsistent Color Behavior in Light Mode**

Description:
Issue Overview:
When using the light mode in the portfolio website, I have noticed that certain colors remain unchanged and do not adapt to the light mode settings.

Expected Behavior:
In light mode, all colors throughout the application should adapt or switch to lighter shades to ensure readability and visual consistency.

Actual Behavior:
Certain elements, such as hero text ,buttons e.t.c  retain their original color scheme when light mode is enabled.

Screenshots or Examples:
<img width="1436" alt="Screenshot 2023-10-05 at 10 10 45" src="https://github.com/Tegacreatives/personal-site/assets/131529321/d2f23387-5229-46f4-a91a-82cf7b76eaaa">

Environment:
Operating System: macOS,
Browser/Platform: Chrome

**Comment by okoraretega** [comment]
Thanks @jjboy55 I'll start working on this
